
epoch:  0 , example:  1  current loss =  2.658543348312378
epoch:  0 , example:  2  current loss =  2.438929319381714
epoch:  0 , example:  3  current loss =  2.2946016788482666
epoch:  1 , example:  4  current loss =  2.1859613060951233
epoch:  1 , example:  5  current loss =  2.103460431098938
epoch:  1 , example:  6  current loss =  2.052064677079519
model checkpoint saved
Traceback (most recent call last):
  File "/media/jonas/B41ED7D91ED792AA/Arbeit_und_Studium/Kognitionswissenschaft/Semester_5/masterarbeit#/data_Code/code/completeTrainScript.py", line 79, in <module>
    functions.trainLoop(dTrain, model, False,"transformerPatches", 0.0001, 0.01, 0.00001, 2, dValidate, 10, True, device)
  File "/media/jonas/B41ED7D91ED792AA/Arbeit_und_Studium/Kognitionswissenschaft/Semester_5/masterarbeit#/data_Code/code/functions.py", line 651, in trainLoop
    trainResults.iloc[validationLosses[i][1], 1] = validationLosses[i][0]
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexing.py", line 818, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexing.py", line 1797, in _setitem_with_indexer
    self._setitem_single_block(indexer, value, name)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexing.py", line 2078, in _setitem_single_block
    self.obj._mgr = self.obj._mgr.setitem(indexer=indexer, value=value)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/internals/managers.py", line 388, in setitem
    return self.apply("setitem", indexer=indexer, value=value)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/internals/managers.py", line 347, in apply
    applied = getattr(b, f)(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/internals/blocks.py", line 984, in setitem
    values[indexer] = casted
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
Traceback (most recent call last):
  File "/media/jonas/B41ED7D91ED792AA/Arbeit_und_Studium/Kognitionswissenschaft/Semester_5/masterarbeit#/data_Code/code/completeTrainScript.py", line 79, in <module>
    functions.trainLoop(dTrain, model, False,"transformerPatches", 0.0001, 0.01, 0.00001, 2, dValidate, 10, True, device)
  File "/media/jonas/B41ED7D91ED792AA/Arbeit_und_Studium/Kognitionswissenschaft/Semester_5/masterarbeit#/data_Code/code/functions.py", line 651, in trainLoop
    trainResults.iloc[validationLosses[i][1], 1] = validationLosses[i][0]
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexing.py", line 818, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexing.py", line 1797, in _setitem_with_indexer
    self._setitem_single_block(indexer, value, name)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexing.py", line 2078, in _setitem_single_block
    self.obj._mgr = self.obj._mgr.setitem(indexer=indexer, value=value)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/internals/managers.py", line 388, in setitem
    return self.apply("setitem", indexer=indexer, value=value)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/internals/managers.py", line 347, in apply
    applied = getattr(b, f)(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/internals/blocks.py", line 984, in setitem
    values[indexer] = casted
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices